// React Native compatible exports for this assets folder

export { default as Kado_dark } from './Kado-dark.svg';
export { default as Kado_light } from './Kado-light.svg';
export { default as X_logo } from './X_logo.svg';
export { default as X_logo_dark } from './X_logo_dark.svg';
export { default as akash } from './akash.svg';
export { default as appstore } from './appstore.svg';
export { default as archId } from './archId.svg';
export { default as avalanche } from './avalanche.svg';
export { default as axelar } from './axelar.svg';
export { default as celestialsId } from './celestialsId.svg';
export { default as compass_circle } from './compass-circle.svg';
export { default as cosmo_station } from './cosmo-station.svg';
export { default as cosmos } from './cosmos.svg';
export { default as dashboard } from './dashboard.svg';
export { default as degens } from './degens.svg';
export { default as generic_dark } from './generic-dark.svg';
export { default as generic_light } from './generic-light.svg';
export { default as generic_nft } from './generic-nft.svg';
export { default as ibc_domains } from './ibc-domains.svg';
export { default as icns } from './icns.svg';
export { default as img_not_available_dark } from './img-not-available-dark.svg';
export { default as img_not_available_light } from './img-not-available-light.svg';
export { default as juno_swap } from './juno-swap.svg';
export { default as juno } from './juno.svg';
export { default as keplr } from './keplr.svg';
export { default as leap_cosmos } from './leap-cosmos.svg';
export { default as leap_custom_dark_mode } from './leap-custom-dark-mode.svg';
export { default as leap_custom_light_mode } from './leap-custom-light-mode.svg';
export { default as leap_logo_28 } from './leap-logo-28.svg';
export { default as leap_logo } from './leap-logo.svg';
export { default as ledger_evm_chains } from './ledger-evm-chains.svg';
export { default as metamask } from './metamask.svg';
export { default as named_skip } from './named-skip.svg';
export { default as nft_logo } from './nft-logo.svg';
export { default as nomic_fullname_logo } from './nomic-fullname-logo.svg';
export { default as osmo } from './osmo.svg';
export { default as osmosis } from './osmosis.svg';
export { default as pallet } from './pallet.svg';
export { default as planq } from './planq.svg';
export { default as playstore } from './playstore.svg';
export { default as secret } from './secret.svg';
export { default as sei_v2 } from './sei-v2.svg';
export { default as sns } from './sns.svg';
export { default as space_id } from './space-id.svg';
export { default as stargaze_names } from './stargaze-names.svg';
export { default as swappedDark } from './swappedDark.svg';
export { default as swappedLight } from './swappedLight.svg';
export { default as terra_station } from './terra-station.svg';
export { default as usdc_logo } from './usdc-logo.svg';
export const bidds = require('./bidds.png');
export const ethereum = require('./ethereum.png');
export const leap_o_logo = require('./leap-o-logo.png');
export const stargaze = require('./stargaze.png');
