// React Native compatible exports for this assets folder

export { default as aave_ethereum } from './aave_ethereum.svg';
export { default as ada_binance } from './ada_binance.svg';
export { default as alter } from './alter.svg';
export { default as angle_down } from './angle-down.svg';
export { default as bac_ethereum } from './bac_ethereum.svg';
export { default as bake_binance } from './bake_binance.svg';
export { default as band_ethereum } from './band_ethereum.svg';
export { default as bat_ethereum } from './bat_ethereum.svg';
export { default as bch_binance } from './bch_binance.svg';
export { default as bnb_binance } from './bnb_binance.svg';
export { default as bunny_binance } from './bunny_binance.svg';
export { default as busd_binance } from './busd_binance.svg';
export { default as cake_binance } from './cake_binance.svg';
export { default as comp_ethereum } from './comp_ethereum.svg';
export { default as dai_ethereum } from './dai_ethereum.svg';
export { default as doge_binance } from './doge_binance.svg';
export { default as dot_binance } from './dot_binance.svg';
export { default as dpi_ethereum } from './dpi_ethereum.svg';
export { default as enj_ethereum } from './enj_ethereum.svg';
export { default as eth_binance } from './eth_binance.svg';
export { default as eth_ethereum } from './eth_ethereum.svg';
export { default as fine_binance } from './fine_binance.svg';
export { default as knc_ethereum } from './knc_ethereum.svg';
export { default as lina_binance } from './lina_binance.svg';
export { default as link_binance } from './link_binance.svg';
export { default as link_ethereum } from './link_ethereum.svg';
export { default as ltc_binance } from './ltc_binance.svg';
export { default as mana_ethereum } from './mana_ethereum.svg';
export { default as mkr_ethereum } from './mkr_ethereum.svg';
export { default as ocean_ethereum } from './ocean_ethereum.svg';
export { default as ren_ethereum } from './ren_ethereum.svg';
export { default as renbtc_ethereum } from './renbtc_ethereum.svg';
export { default as rsr_ethereum } from './rsr_ethereum.svg';
export { default as rune_ethereum } from './rune_ethereum.svg';
export { default as salpha } from './salpha.svg';
export { default as scrt } from './scrt.svg';
export { default as sefi } from './sefi.svg';
export { default as selenian } from './selenian.svg';
export { default as shade } from './shade.svg';
export { default as sienna } from './sienna.svg';
export { default as snx_ethereum } from './snx_ethereum.svg';
export { default as sscrt } from './sscrt.svg';
export { default as sushi_ethereum } from './sushi_ethereum.svg';
export { default as torn_ethereum } from './torn_ethereum.svg';
export { default as trx_binance } from './trx_binance.svg';
export { default as tusd_ethereum } from './tusd_ethereum.svg';
export { default as uni_ethereum } from './uni_ethereum.svg';
export { default as unilp_ethereum } from './unilp_ethereum.svg';
export { default as usdc_binance } from './usdc_binance.svg';
export { default as usdc_ethereum } from './usdc_ethereum.svg';
export { default as usdt_binance } from './usdt_binance.svg';
export { default as usdt_ethereum } from './usdt_ethereum.svg';
export { default as wallet_icon } from './wallet-icon.svg';
export { default as wbtc_ethereum } from './wbtc_ethereum.svg';
export { default as xrp_binance } from './xrp_binance.svg';
export { default as xvs_binance } from './xvs_binance.svg';
export { default as yfi_ethereum } from './yfi_ethereum.svg';
export { default as yfl_ethereum } from './yfl_ethereum.svg';
export { default as zrx_ethereum } from './zrx_ethereum.svg';
export const atom = require('./atom.png');
export const btn_purple_background = require('./btn_purple_background.png');
export const dvpn = require('./dvpn.png');
export const fat_secret = require('./fat_secret.png');
export const huahua = require('./huahua.png');
export const luna = require('./luna.png');
export const osmo = require('./osmo.png');
export const sXMR = require('./sXMR.png');
export const sescrt = require('./sescrt.png');
export const ust = require('./ust.png');
